animations: (
    {
        match = "window_type = 'normal'";
        animations = (
            {
                triggers = ["open"];
                opacity = {
                    curve = "cubic-bezier(0,1,1,1)";
                    duration = 0.3;
                    start = 0;
                    end = "window-raw-opacity";
                };
            },
            {
                triggers = ["close"];
                opacity = {
                    curve = "cubic-bezier(0,1,1,1)";
                    duration = 0.3;
                    start = "window-raw-opacity-before";
                    end = 0;
                };
            }
        )
    }
);
